joint_order: [waist, shoulder, elbow, forearm_roll, wrist_angle, wrist_rotate, gripper]
sleep_positions: [0, -1.80, 1.55, 0, -1.57, 0, 0]

joint_state_publisher:
  update_rate: 100
  publish_states: true
  topic_name: joint_states

groups:
  arm: [waist, shoulder, elbow, forearm_roll, wrist_angle, wrist_rotate]

grippers:
  gripper:
    horn_radius: 0.020
    arm_length: 0.020
    left_finger: left_finger
    right_finger: right_finger

#キャリブレーションしない設定
shadows:

sisters:

motors:
  waist:
    ID: 1
    Baud_Rate: 3

  shoulder:
    ID: 2
    Baud_Rate: 3    

  elbow:
    ID: 4
    Baud_Rate: 3

  forearm_roll:
    ID: 6
    Baud_Rate: 3

  wrist_angle:
    ID: 7
    Baud_Rate: 3

  wrist_rotate:
    ID: 8
    Baud_Rate: 3

  gripper:
    ID: 9
    Baud_Rate: 3